# Generated by Django 3.2.9 on 2021-11-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('img1', models.ImageField(upload_to='items')),
                ('img2', models.ImageField(upload_to='items')),
                ('img3', models.ImageField(upload_to='items')),
                ('img4', models.ImageField(upload_to='items')),
                ('img5', models.ImageField(upload_to='items')),
            ],
        ),
    ]
