# Generated by Django 3.2.9 on 2021-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_details',
            name='img2',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='land_details',
            name='img3',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='land_details',
            name='img4',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='land_details',
            name='img5',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
